# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - github-api-gateway

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_09adb0d4f79340ec94f49e5f4bdf4758 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9e241cc9cb284a06ba05c1fc714f8445 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_09adb0d4f79340ec94f49e5f4bdf4758 }}/github-api-gateway:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'github-api-gateway'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9f77e27ae91d4394ad0f51fa07f7bbee }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_09adb0d4f79340ec94f49e5f4bdf4758 }}/github-api-gateway:${{ github.sha }}'